apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/avikjis27/demo-apps.git
    path: nodejs-webapp/kustomize/overlays/qa
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: qa
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      selfHeal: true
      prune: true
